#!/bin/sh

python extractor_03.py ../../data_capture/image_data_capture/ ../../data_capture/key_data_capture/ ../../dictionaries/ 20121128_1539_11 6 ../../generated_feature_vectors/

python extractor_03.py ../../data_capture/image_data_capture/ ../../data_capture/key_data_capture/ ../../dictionaries/ 20121207_1349_57 6 ../../generated_feature_vectors/

python extractor_03.py ../../data_capture/image_data_capture/ ../../data_capture/key_data_capture/ ../../dictionaries/ 20121207_1423_02 6 ../../generated_feature_vectors/

python extractor_03.py ../../data_capture/image_data_capture/ ../../data_capture/key_data_capture/ ../../dictionaries/ 20121207_1716_00_nbc_agg 6 ../../generated_feature_vectors/

